### ISSUE TITLE
Error in archive.list(callback)

### ISSUE THREAD

**Issue by vucuong12** [burkostya/node-unrar#5]
![error](https://cloud.githubusercontent.com/assets/11524188/9266806/38253f88-4270-11e5-8ce0-6512aa5b9b7c.png)

I try to run this code:

var Unrar = require('unrar');
var path = require('path');
var archivePath = path.resolve(__dirname, 'test.rar');
var archive = new Unrar(archivePath);

archive.list(function (err, entries) {
	if (err) {console.log(err); return}
	console.log(entries);
});

But the error appeared like this:

{ [Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "unrar vt D:\project                          \hehe\test.rar"
'unrar' is not recognized as an internal or external command,
operable program or batch file.
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe /s /c "unrar vt D:\\project\\hehe\\test.rar"' }

Can you help me out?
Thanks in advance.

**Comment by burkostya** [comment]
This module uses `unrar` program and your system can't find it. You should add the path to directory with `unrar` binary to `PATH` environment variable. I don't remember how to do this in windows. Google should help :)
If you don't have installed unrar, download it from official site http://www.rarlab.com/rar_add.htm

**Comment by burkostya** [comment]
Feel free to reopen

**Comment by susan51531** [comment]
@burkostya better mention  [http://www.rarlab.com/rar_add.htm](http://www.rarlab.com/rar_add.htm) in the README.md
Also should replace unrar-fee to it under ubuntu.

**Comment by burkostya** [comment]
@susan51531 Done
